### ISSUE TITLE
Auto depoly gh-pages with continuous integration

### ISSUE THREAD

**Issue by jacobcarpenter** [hackbellingham/member-graph#12]
Having to run the `process-links` node script before publishing the data is burdensome. It should be possible to create the proper merged object at runtime.

**Comment by theRocket** [comment]
I'm rewriting this script to add relations as an attribute to a linkage, so give me a heads up if the processing code changes significantly. I'm using it as a way to understand Javascript array functions!

**Comment by jacobcarpenter** [comment]
Another possibility would be to create some kind of Continuous Integration hook to automatically run the script and publish its output to the gh-pages branch.

... actually, that sounds really convenient!

**Comment by jacobcarpenter** [comment]
Something like this:

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd or https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db#.9ou056ili or any of the rest of these https://www.google.com/search?q=travis+ci+publish+gh-pages

**Comment by jacobcarpenter** [comment]
Thanks, so much @tantalic for implementing this!
